version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped

  # Optional: Add database service
  # database:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: ragdb
  #     POSTGRES_USER: raguser
  #     POSTGRES_PASSWORD: ragpass
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:

